import { MigrationInterface, QueryRunner } from "typeorm";

export class AddMissingColumns1750517921438 implements MigrationInterface {
    name = 'AddMissingColumns1750517921438'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "team_members" DROP CONSTRAINT "team_members_user_clerk_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "clients_created_by_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "projects_client_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "projects_created_by_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "documents_project_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "documents_uploaded_by_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "reports_project_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "reports_created_by_user_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_clerk_clerk_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_clients_created_by"`);
        await queryRunner.query(`DROP INDEX "public"."idx_projects_client_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_projects_created_by"`);
        await queryRunner.query(`DROP INDEX "public"."idx_documents_project_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reports_project_id"`);
        await queryRunner.query(`CREATE TABLE "document_versions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "document_id" uuid NOT NULL, "version_number" integer NOT NULL, "storage_url" text NOT NULL, "comments" text, "created_by_user_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_baf26dab035c6d6fc433f9dc6a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP CONSTRAINT "users_clerk_clerk_user_id_key"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP COLUMN "clerk_user_id"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "client_id"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "start_date"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "end_date"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "progress"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "project_type"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "project_area"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "room_count"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "image_url"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "created_by_user_id"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "in_charge"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD "clerkId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD CONSTRAINT "UQ_1f9ebfa3c80daf74d995c09e59f" UNIQUE ("clerkId")`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD "firstName" character varying`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD "lastName" character varying`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD "profileImageUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD "roles" text NOT NULL DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "description" character varying`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "address" character varying`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "city" character varying`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "postalCode" character varying`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "budget" integer`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "startDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "endDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "thumbnail" character varying`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "ownerId" character varying`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "tags" text`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "clientId" uuid`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "inCharge" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP CONSTRAINT "users_clerk_email_key"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD "email" character varying`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP CONSTRAINT "team_members_email_key"`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "company_name"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "company_name" character varying`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "clients_email_key"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "email" character varying`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "status" character varying`);
        await queryRunner.query(`ALTER TABLE "documents" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "documents" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "documents" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "documents" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "documents" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "documents" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "reports_report_number_key"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "visit_date"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "visit_date" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD CONSTRAINT "FK_34bdb401c3d20d17e0a34d9609f" FOREIGN KEY ("user_clerk_id") REFERENCES "users_clerk"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "FK_d0285a96f82152e543d76600e18" FOREIGN KEY ("created_by_user_id") REFERENCES "users_clerk"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_091f9433895a53408cb8ae3864f" FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_e156b298c20873e14c362e789bf" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_6f8986d1406171fccbd6bb2d864" FOREIGN KEY ("uploaded_by_user_id") REFERENCES "users_clerk"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_bbe3b065e71d60f9d51ad236225" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_570a3e4f35a7f96c2cd66de10fe" FOREIGN KEY ("created_by_user_id") REFERENCES "users_clerk"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_versions" ADD CONSTRAINT "FK_ac75577bca976d6d581b0f459b6" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_versions" ADD CONSTRAINT "FK_aed50da755537531cb0fcdc10ae" FOREIGN KEY ("created_by_user_id") REFERENCES "users_clerk"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "document_versions" DROP CONSTRAINT "FK_aed50da755537531cb0fcdc10ae"`);
        await queryRunner.query(`ALTER TABLE "document_versions" DROP CONSTRAINT "FK_ac75577bca976d6d581b0f459b6"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_570a3e4f35a7f96c2cd66de10fe"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_bbe3b065e71d60f9d51ad236225"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_6f8986d1406171fccbd6bb2d864"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_e156b298c20873e14c362e789bf"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_091f9433895a53408cb8ae3864f"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "FK_d0285a96f82152e543d76600e18"`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP CONSTRAINT "FK_34bdb401c3d20d17e0a34d9609f"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "visit_date"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "visit_date" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "reports_report_number_key" UNIQUE ("report_number")`);
        await queryRunner.query(`ALTER TABLE "documents" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "documents" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "documents" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "documents" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "documents" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "documents" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "status" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "email" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "clients_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "company_name"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "company_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD "email" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD CONSTRAINT "team_members_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD "email" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD CONSTRAINT "users_clerk_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "inCharge"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "clientId"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "tags"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "ownerId"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "thumbnail"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "endDate"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "startDate"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "budget"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "postalCode"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "city"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP COLUMN "roles"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP COLUMN "profileImageUrl"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP COLUMN "lastName"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP COLUMN "firstName"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP CONSTRAINT "UQ_1f9ebfa3c80daf74d995c09e59f"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP COLUMN "clerkId"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "in_charge" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "created_by_user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "image_url" text`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "room_count" integer`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "project_area" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "project_type" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "progress" integer DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "end_date" date`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "start_date" date`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "location" text`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "client_id" uuid`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD "name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD "clerk_user_id" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD CONSTRAINT "users_clerk_clerk_user_id_key" UNIQUE ("clerk_user_id")`);
        await queryRunner.query(`DROP TABLE "document_versions"`);
        await queryRunner.query(`CREATE INDEX "idx_reports_project_id" ON "reports" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "idx_documents_project_id" ON "documents" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "idx_projects_created_by" ON "projects" ("created_by_user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_projects_client_id" ON "projects" ("client_id") `);
        await queryRunner.query(`CREATE INDEX "idx_clients_created_by" ON "clients" ("created_by_user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_users_clerk_clerk_user_id" ON "users_clerk" ("clerk_user_id") `);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "reports_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "users_clerk"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "reports_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "documents_uploaded_by_user_id_fkey" FOREIGN KEY ("uploaded_by_user_id") REFERENCES "users_clerk"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "documents_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "projects_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "users_clerk"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "projects_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "clients_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "users_clerk"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD CONSTRAINT "team_members_user_clerk_id_fkey" FOREIGN KEY ("user_clerk_id") REFERENCES "users_clerk"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
