import { MigrationInterface, QueryRunner } from "typeorm";

export class AddClerkIdToUsersClerk1751158950820 implements MigrationInterface {
    name = 'AddClerkIdToUsersClerk1751158950820'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "team_members" DROP CONSTRAINT "team_members_user_clerk_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "reports_project_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "reports_created_by_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "project_team_members" DROP CONSTRAINT "project_team_members_project_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "project_team_members" DROP CONSTRAINT "project_team_members_team_member_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "projects_client_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "projects_created_by_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "report_photos" DROP CONSTRAINT "report_photos_report_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "documents_project_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "documents_uploaded_by_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "clients_created_by_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "descriptifs" DROP CONSTRAINT "descriptifs_project_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "annotations" DROP CONSTRAINT "annotations_document_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "annotations" DROP CONSTRAINT "annotations_created_by_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "annotations" DROP CONSTRAINT "annotations_resolved_by_user_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_clerk_clerk_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reports_project_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_project_team_members_project_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_project_team_members_team_member_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_projects_client_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_projects_created_by"`);
        await queryRunner.query(`DROP INDEX "public"."idx_report_photos_report_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_documents_project_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_clients_created_by"`);
        await queryRunner.query(`DROP INDEX "public"."idx_descriptifs_project_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_annotations_document_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_annotations_created_by"`);
        await queryRunner.query(`CREATE TABLE "document_versions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "document_id" uuid NOT NULL, "version_number" integer NOT NULL, "storage_url" text NOT NULL, "comments" text, "created_by_user_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_baf26dab035c6d6fc433f9dc6a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP CONSTRAINT "users_clerk_clerk_user_id_key"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP COLUMN "clerk_user_id"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD "clerk_user_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD "name" character varying`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD "clerkId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD CONSTRAINT "UQ_1f9ebfa3c80daf74d995c09e59f" UNIQUE ("clerkId")`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD "firstName" character varying`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD "lastName" character varying`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD "profileImageUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD "roles" text NOT NULL DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP CONSTRAINT "users_clerk_email_key"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD "email" character varying`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP COLUMN "user_clerk_id"`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD "user_clerk_id" character varying`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP CONSTRAINT "team_members_email_key"`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP COLUMN "role"`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD "role" character varying`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD "status" character varying DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP COLUMN "avatar_url"`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD "avatar_url" character varying`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP COLUMN "user_clerk_id"`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD "user_clerk_id" uuid`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP COLUMN "role"`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD "role" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD "status" character varying(50) DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP COLUMN "avatar_url"`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD "avatar_url" text`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "project_id"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "project_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "reports_report_number_key"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "report_number"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "report_number" character varying`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "visit_date"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "visit_date" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "contractor"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "contractor" character varying`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "in_charge"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "in_charge" character varying`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "weather"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "weather" character varying`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "additional_details"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "additional_details" character varying`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "created_by_user_id"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "created_by_user_id" character varying`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "project_team_members" DROP CONSTRAINT "project_team_members_pkey"`);
        await queryRunner.query(`ALTER TABLE "project_team_members" ADD CONSTRAINT "project_team_members_pkey" PRIMARY KEY ("team_member_id")`);
        await queryRunner.query(`ALTER TABLE "project_team_members" DROP COLUMN "project_id"`);
        await queryRunner.query(`ALTER TABLE "project_team_members" ADD "project_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "project_team_members" DROP CONSTRAINT "project_team_members_pkey"`);
        await queryRunner.query(`ALTER TABLE "project_team_members" ADD CONSTRAINT "project_team_members_pkey" PRIMARY KEY ("team_member_id", "project_id")`);
        await queryRunner.query(`ALTER TABLE "project_team_members" DROP CONSTRAINT "project_team_members_pkey"`);
        await queryRunner.query(`ALTER TABLE "project_team_members" ADD CONSTRAINT "PK_c1a8ad2f15c8b55e6f6ab702604" PRIMARY KEY ("project_id")`);
        await queryRunner.query(`ALTER TABLE "project_team_members" DROP COLUMN "team_member_id"`);
        await queryRunner.query(`ALTER TABLE "project_team_members" ADD "team_member_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "project_team_members" DROP CONSTRAINT "PK_c1a8ad2f15c8b55e6f6ab702604"`);
        await queryRunner.query(`ALTER TABLE "project_team_members" ADD CONSTRAINT "PK_407ca9a2be06acceb85c699ae96" PRIMARY KEY ("project_id", "team_member_id")`);
        await queryRunner.query(`ALTER TABLE "project_team_members" DROP COLUMN "role_in_project"`);
        await queryRunner.query(`ALTER TABLE "project_team_members" ADD "role_in_project" character varying`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "name" character varying`);
        await queryRunner.query(`UPDATE "projects" SET "name" = 'Projet sans nom' WHERE "name" IS NULL`);
        await queryRunner.query(`ALTER TABLE "projects" ALTER COLUMN "name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "client_id"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "client_id" character varying`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "location" character varying`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "start_date"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "start_date" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "end_date"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "end_date" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "status" character varying`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "project_type"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "project_type" character varying`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "project_area"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "project_area" integer`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "image_url"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "image_url" character varying`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "created_by_user_id"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "created_by_user_id" character varying`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "report_photos" DROP COLUMN "report_id"`);
        await queryRunner.query(`ALTER TABLE "report_photos" ADD "report_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report_photos" DROP COLUMN "photo_url"`);
        await queryRunner.query(`ALTER TABLE "report_photos" ADD "photo_url" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report_photos" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "report_photos" ADD "description" character varying`);
        await queryRunner.query(`ALTER TABLE "report_photos" DROP COLUMN "taken_at"`);
        await queryRunner.query(`ALTER TABLE "report_photos" ADD "taken_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "report_photos" DROP COLUMN "uploaded_at"`);
        await queryRunner.query(`ALTER TABLE "report_photos" ADD "uploaded_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "documents" DROP COLUMN "project_id"`);
        await queryRunner.query(`ALTER TABLE "documents" ADD "project_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "documents" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "documents" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "documents" DROP COLUMN "file_type"`);
        await queryRunner.query(`ALTER TABLE "documents" ADD "file_type" character varying`);
        await queryRunner.query(`ALTER TABLE "documents" DROP COLUMN "storage_url"`);
        await queryRunner.query(`ALTER TABLE "documents" ADD "storage_url" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "documents" DROP COLUMN "uploaded_by_user_id"`);
        await queryRunner.query(`ALTER TABLE "documents" ADD "uploaded_by_user_id" character varying`);
        await queryRunner.query(`ALTER TABLE "documents" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "documents" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "documents" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "documents" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "company_name"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "company_name" character varying`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "clients_email_key"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "email" character varying`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "phone" character varying`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "address" character varying`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "created_by_user_id"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "created_by_user_id" character varying`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "descriptifs" DROP COLUMN "project_id"`);
        await queryRunner.query(`ALTER TABLE "descriptifs" ADD "project_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "descriptifs" DROP COLUMN "lot_name"`);
        await queryRunner.query(`ALTER TABLE "descriptifs" ADD "lot_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "descriptifs" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "descriptifs" ADD "description" character varying`);
        await queryRunner.query(`ALTER TABLE "descriptifs" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "descriptifs" ADD "status" character varying`);
        await queryRunner.query(`ALTER TABLE "descriptifs" DROP COLUMN "budget"`);
        await queryRunner.query(`ALTER TABLE "descriptifs" ADD "budget" integer`);
        await queryRunner.query(`ALTER TABLE "descriptifs" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "descriptifs" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "descriptifs" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "descriptifs" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "annotations" DROP COLUMN "document_id"`);
        await queryRunner.query(`ALTER TABLE "annotations" ADD "document_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "annotations" DROP COLUMN "created_by_user_id"`);
        await queryRunner.query(`ALTER TABLE "annotations" ADD "created_by_user_id" character varying`);
        await queryRunner.query(`ALTER TABLE "annotations" DROP COLUMN "comment"`);
        await queryRunner.query(`ALTER TABLE "annotations" ADD "comment" character varying`);
        await queryRunner.query(`ALTER TABLE "annotations" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "annotations" ADD "type" character varying DEFAULT 'comment'`);
        await queryRunner.query(`ALTER TABLE "annotations" DROP COLUMN "resolved_at"`);
        await queryRunner.query(`ALTER TABLE "annotations" ADD "resolved_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "annotations" DROP COLUMN "resolved_by_user_id"`);
        await queryRunner.query(`ALTER TABLE "annotations" ADD "resolved_by_user_id" character varying`);
        await queryRunner.query(`ALTER TABLE "annotations" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "annotations" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "annotations" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "annotations" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD CONSTRAINT "FK_34bdb401c3d20d17e0a34d9609f" FOREIGN KEY ("user_clerk_id") REFERENCES "users_clerk"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_versions" ADD CONSTRAINT "FK_ac75577bca976d6d581b0f459b6" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_versions" ADD CONSTRAINT "FK_aed50da755537531cb0fcdc10ae" FOREIGN KEY ("created_by_user_id") REFERENCES "users_clerk"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "document_versions" DROP CONSTRAINT "FK_aed50da755537531cb0fcdc10ae"`);
        await queryRunner.query(`ALTER TABLE "document_versions" DROP CONSTRAINT "FK_ac75577bca976d6d581b0f459b6"`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP CONSTRAINT "FK_34bdb401c3d20d17e0a34d9609f"`);
        await queryRunner.query(`ALTER TABLE "annotations" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "annotations" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "annotations" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "annotations" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "annotations" DROP COLUMN "resolved_by_user_id"`);
        await queryRunner.query(`ALTER TABLE "annotations" ADD "resolved_by_user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "annotations" DROP COLUMN "resolved_at"`);
        await queryRunner.query(`ALTER TABLE "annotations" ADD "resolved_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "annotations" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "annotations" ADD "type" character varying(50) DEFAULT 'comment'`);
        await queryRunner.query(`ALTER TABLE "annotations" DROP COLUMN "comment"`);
        await queryRunner.query(`ALTER TABLE "annotations" ADD "comment" text`);
        await queryRunner.query(`ALTER TABLE "annotations" DROP COLUMN "created_by_user_id"`);
        await queryRunner.query(`ALTER TABLE "annotations" ADD "created_by_user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "annotations" DROP COLUMN "document_id"`);
        await queryRunner.query(`ALTER TABLE "annotations" ADD "document_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "descriptifs" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "descriptifs" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "descriptifs" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "descriptifs" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "descriptifs" DROP COLUMN "budget"`);
        await queryRunner.query(`ALTER TABLE "descriptifs" ADD "budget" numeric(12,2)`);
        await queryRunner.query(`ALTER TABLE "descriptifs" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "descriptifs" ADD "status" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "descriptifs" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "descriptifs" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "descriptifs" DROP COLUMN "lot_name"`);
        await queryRunner.query(`ALTER TABLE "descriptifs" ADD "lot_name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "descriptifs" DROP COLUMN "project_id"`);
        await queryRunner.query(`ALTER TABLE "descriptifs" ADD "project_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "created_by_user_id"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "created_by_user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "address" text`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "phone" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "email" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "clients_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "company_name"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "company_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "documents" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "documents" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "documents" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "documents" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "documents" DROP COLUMN "uploaded_by_user_id"`);
        await queryRunner.query(`ALTER TABLE "documents" ADD "uploaded_by_user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "documents" DROP COLUMN "storage_url"`);
        await queryRunner.query(`ALTER TABLE "documents" ADD "storage_url" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "documents" DROP COLUMN "file_type"`);
        await queryRunner.query(`ALTER TABLE "documents" ADD "file_type" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "documents" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "documents" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "documents" DROP COLUMN "project_id"`);
        await queryRunner.query(`ALTER TABLE "documents" ADD "project_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report_photos" DROP COLUMN "uploaded_at"`);
        await queryRunner.query(`ALTER TABLE "report_photos" ADD "uploaded_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "report_photos" DROP COLUMN "taken_at"`);
        await queryRunner.query(`ALTER TABLE "report_photos" ADD "taken_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "report_photos" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "report_photos" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "report_photos" DROP COLUMN "photo_url"`);
        await queryRunner.query(`ALTER TABLE "report_photos" ADD "photo_url" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report_photos" DROP COLUMN "report_id"`);
        await queryRunner.query(`ALTER TABLE "report_photos" ADD "report_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "created_by_user_id"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "created_by_user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "image_url"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "image_url" text`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "project_area"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "project_area" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "project_type"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "project_type" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "status" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "end_date"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "end_date" date`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "start_date"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "start_date" date`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "location" text`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "client_id"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "client_id" uuid`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "project_team_members" DROP COLUMN "role_in_project"`);
        await queryRunner.query(`ALTER TABLE "project_team_members" ADD "role_in_project" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "project_team_members" DROP CONSTRAINT "PK_407ca9a2be06acceb85c699ae96"`);
        await queryRunner.query(`ALTER TABLE "project_team_members" ADD CONSTRAINT "PK_c1a8ad2f15c8b55e6f6ab702604" PRIMARY KEY ("project_id")`);
        await queryRunner.query(`ALTER TABLE "project_team_members" DROP COLUMN "team_member_id"`);
        await queryRunner.query(`ALTER TABLE "project_team_members" ADD "team_member_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "project_team_members" DROP CONSTRAINT "PK_c1a8ad2f15c8b55e6f6ab702604"`);
        await queryRunner.query(`ALTER TABLE "project_team_members" ADD CONSTRAINT "project_team_members_pkey" PRIMARY KEY ("team_member_id", "project_id")`);
        await queryRunner.query(`ALTER TABLE "project_team_members" DROP CONSTRAINT "project_team_members_pkey"`);
        await queryRunner.query(`ALTER TABLE "project_team_members" ADD CONSTRAINT "project_team_members_pkey" PRIMARY KEY ("team_member_id")`);
        await queryRunner.query(`ALTER TABLE "project_team_members" DROP COLUMN "project_id"`);
        await queryRunner.query(`ALTER TABLE "project_team_members" ADD "project_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "project_team_members" DROP CONSTRAINT "project_team_members_pkey"`);
        await queryRunner.query(`ALTER TABLE "project_team_members" ADD CONSTRAINT "project_team_members_pkey" PRIMARY KEY ("project_id", "team_member_id")`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "created_by_user_id"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "created_by_user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "additional_details"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "additional_details" text`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "weather"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "weather" text`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "in_charge"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "in_charge" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "contractor"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "contractor" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "visit_date"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "visit_date" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "report_number"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "report_number" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "reports_report_number_key" UNIQUE ("report_number")`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "project_id"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "project_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP COLUMN "avatar_url"`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD "avatar_url" character varying`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD "status" character varying DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP COLUMN "role"`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD "role" character varying`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP COLUMN "user_clerk_id"`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD "user_clerk_id" character varying`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP COLUMN "avatar_url"`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD "avatar_url" text`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD "status" character varying(50) DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP COLUMN "role"`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD "role" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD "email" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD CONSTRAINT "team_members_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP COLUMN "user_clerk_id"`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD "user_clerk_id" uuid`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD "email" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD CONSTRAINT "users_clerk_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP COLUMN "roles"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP COLUMN "profileImageUrl"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP COLUMN "lastName"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP COLUMN "firstName"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP CONSTRAINT "UQ_1f9ebfa3c80daf74d995c09e59f"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP COLUMN "clerkId"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" DROP COLUMN "clerk_user_id"`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD "name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD "clerk_user_id" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users_clerk" ADD CONSTRAINT "users_clerk_clerk_user_id_key" UNIQUE ("clerk_user_id")`);
        await queryRunner.query(`DROP TABLE "document_versions"`);
        await queryRunner.query(`CREATE INDEX "idx_annotations_created_by" ON "annotations" ("created_by_user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_annotations_document_id" ON "annotations" ("document_id") `);
        await queryRunner.query(`CREATE INDEX "idx_descriptifs_project_id" ON "descriptifs" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "idx_clients_created_by" ON "clients" ("created_by_user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_documents_project_id" ON "documents" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "idx_report_photos_report_id" ON "report_photos" ("report_id") `);
        await queryRunner.query(`CREATE INDEX "idx_projects_created_by" ON "projects" ("created_by_user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_projects_client_id" ON "projects" ("client_id") `);
        await queryRunner.query(`CREATE INDEX "idx_project_team_members_team_member_id" ON "project_team_members" ("team_member_id") `);
        await queryRunner.query(`CREATE INDEX "idx_project_team_members_project_id" ON "project_team_members" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "idx_reports_project_id" ON "reports" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "idx_users_clerk_clerk_user_id" ON "users_clerk" ("clerk_user_id") `);
        await queryRunner.query(`ALTER TABLE "annotations" ADD CONSTRAINT "annotations_resolved_by_user_id_fkey" FOREIGN KEY ("resolved_by_user_id") REFERENCES "users_clerk"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "annotations" ADD CONSTRAINT "annotations_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "users_clerk"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "annotations" ADD CONSTRAINT "annotations_document_id_fkey" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "descriptifs" ADD CONSTRAINT "descriptifs_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "clients_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "users_clerk"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "documents_uploaded_by_user_id_fkey" FOREIGN KEY ("uploaded_by_user_id") REFERENCES "users_clerk"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "documents_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_photos" ADD CONSTRAINT "report_photos_report_id_fkey" FOREIGN KEY ("report_id") REFERENCES "reports"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "projects_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "users_clerk"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "projects_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_team_members" ADD CONSTRAINT "project_team_members_team_member_id_fkey" FOREIGN KEY ("team_member_id") REFERENCES "team_members"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_team_members" ADD CONSTRAINT "project_team_members_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "reports_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "users_clerk"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "reports_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD CONSTRAINT "team_members_user_clerk_id_fkey" FOREIGN KEY ("user_clerk_id") REFERENCES "users_clerk"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
