
import { Resource } from "./types";

export const resources: Resource[] = [
  {
    id: "1",
    name: "Template_projet_résidentiel.dwg",
    type: "document",
    category: "templates",
    size: "4.2 MB",
    uploadedBy: "Sophie Laurent",
    uploadedAt: "2023-03-15",
    downloads: 145,
  },
  {
    id: "2",
    name: "RT2020_normes_thermiques.pdf",
    type: "document",
    category: "standards",
    size: "2.8 MB",
    uploadedBy: "Jean Moreau",
    uploadedAt: "2023-01-22",
    downloads: 87,
  },
  {
    id: "3",
    name: "Catalogue_materiaux_2023.pdf",
    type: "document",
    category: "materials",
    size: "15.6 MB",
    uploadedBy: "Marie Lefevre",
    uploadedAt: "2023-02-10",
    downloads: 210,
  },
  {
    id: "4",
    name: "Tutoriel_Revit_débutant.mp4",
    type: "video",
    category: "tutorials",
    size: "328.5 MB",
    uploadedBy: "Antoine Girard",
    uploadedAt: "2022-11-05",
    downloads: 321,
  },
  {
    id: "5",
    name: "Plans_fondation_standard.dwg",
    type: "document",
    category: "templates",
    size: "3.9 MB",
    uploadedBy: "Thomas Dubois",
    uploadedAt: "2023-04-02",
    downloads: 65,
  },
  {
    id: "6",
    name: "Textures_marbre_HD.zip",
    type: "archive",
    category: "materials",
    size: "128.2 MB",
    uploadedBy: "Camille Bernard",
    uploadedAt: "2023-03-18",
    downloads: 142,
  },
  {
    id: "7",
    name: "Normes_PMR_2023.pdf",
    type: "document",
    category: "standards",
    size: "5.3 MB",
    uploadedBy: "Jean Moreau",
    uploadedAt: "2023-02-28",
    downloads: 98,
  },
  {
    id: "8",
    name: "Rendu_exemple_photoréaliste.jpg",
    type: "image",
    category: "tutorials",
    size: "8.7 MB",
    uploadedBy: "Sophie Laurent",
    uploadedAt: "2023-01-15",
    downloads: 187,
  },
  {
    id: "9",
    name: "Plugins_SketchUp_2023.zip",
    type: "archive",
    category: "software",
    size: "45.8 MB",
    uploadedBy: "Antoine Girard",
    uploadedAt: "2023-03-25",
    downloads: 234,
  },
  {
    id: "10",
    name: "Formation_BIM_avancé.mp4",
    type: "video",
    category: "tutorials",
    size: "512.3 MB",
    uploadedBy: "Antoine Girard",
    uploadedAt: "2023-02-12",
    downloads: 156,
  },
];
