// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsmnsyrfmfkysgbhtkuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzbW5zeXJmbWZreXNnYmh0a3VvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxOTY2NjIsImV4cCI6MjA1ODc3MjY2Mn0.ZidTe3NZ1eBoh6osVbvb6YkI7i4W2aOde0qmzOIDgno";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);